# Generated by Django 3.2.8 on 2021-11-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211011_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_news', models.CharField(max_length=200)),
                ('prew_text', models.TextField()),
                ('core_text', models.TextField()),
                ('image_news', models.ImageField(blank=True, null=True, upload_to='news_pic/')),
            ],
        ),
    ]
