# Generated by Django 3.2.8 on 2021-11-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='core_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='prew_text',
            field=models.TextField(max_length=1000),
        ),
    ]
