# Generated by Django 3.2.8 on 2021-11-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_order_phone'),
        ('accounts', '0002_auto_20211105_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='orders',
            field=models.ManyToManyField(default=1, related_name='related_customer', to='cart.Order', verbose_name='Заказы покупателя'),
        ),
    ]
