# Generated by Django 3.2.8 on 2021-11-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
