# Generated by Django 2.2.6 on 2021-10-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_customer', to='cart.Order', verbose_name='Заказы покупателя'),
        ),
    ]
