# Generated by Django 2.2.6 on 2021-10-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20211011_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products_in_the_cart',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
