# Generated by Django 3.2.8 on 2021-11-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
    ]
