# Generated by Django 2.2.6 on 2021-10-11 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_products_in_the_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products_in_the_cart',
        ),
    ]
